version: "3.7"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: exemple-api
        volumes:
            - ./src:/app/src
        ports:
            - "8080:8080"
            - "8181:8181"
        command: npm run dev
